import { StyleSheet } from 'react-native'

export const colors = {
  primary: '#0b032d',
  secondary: '#a833b9',
  tertiary: '#f1eded',
  bgElevated: '#160a3a',
  border: '#2e1660',
  success: '#4caf50',
  warning: '#ffc107',
  danger: '#ff6b6b',
}

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.primary,
    padding: 24,
    justifyContent: 'center',
  },
  screenTop: {
    flex: 1,
    backgroundColor: colors.primary,
    padding: 24,
    paddingTop: 60,
  },
  logo: {
    fontSize: 26,
    fontWeight: '700',
    color: colors.tertiary,
    textAlign: 'center',
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 13,
    color: 'rgba(241,237,237,0.6)',
    textAlign: 'center',
    marginBottom: 28,
  },
  label: {
    fontSize: 12,
    color: 'rgba(241,237,237,0.7)',
    marginBottom: 6,
    marginTop: 14,
  },
  input: {
    backgroundColor: colors.bgElevated,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
    color: colors.tertiary,
    fontSize: 15,
  },
  button: {
    marginTop: 22,
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: colors.secondary,
    alignItems: 'center',
  },
  buttonText: { color: '#fff', fontWeight: '700', fontSize: 15 },
  buttonDisabled: { opacity: 0.6 },
  buttonSecondary: {
    marginTop: 20,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
  },
  buttonSecondaryText: { color: 'rgba(241,237,237,0.7)', fontWeight: '600' },
  hint: {
    fontSize: 11,
    color: 'rgba(241,237,237,0.4)',
    textAlign: 'center',
    marginTop: 16,
    lineHeight: 16,
  },
  errorBox: {
    backgroundColor: 'rgba(220,53,69,0.15)',
    borderWidth: 1,
    borderColor: 'rgba(220,53,69,0.4)',
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
  },
  errorText: { color: '#ff9aa6', fontSize: 12 },
  statusRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 6 },
  statusDot: { width: 10, height: 10, borderRadius: 5, marginRight: 8 },
  statusText: { fontSize: 16, fontWeight: '700', color: colors.tertiary },
  metaLine: { fontSize: 12, color: 'rgba(241,237,237,0.6)', marginBottom: 2 },
  sectionCard: {
    backgroundColor: colors.bgElevated,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 16,
    marginTop: 18,
  },
  sectionTitle: { fontSize: 14, fontWeight: '700', color: colors.tertiary, marginBottom: 4 },
  sectionDesc: { fontSize: 12, color: 'rgba(241,237,237,0.6)', lineHeight: 17, marginBottom: 10 },
  proLockRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(168,51,185,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(168,51,185,0.3)',
    borderRadius: 8,
    padding: 10,
  },
  proLockText: { color: colors.secondary, fontSize: 12, fontWeight: '600', flex: 1, marginRight: 8 },
  toggleOn: { backgroundColor: colors.success },
  toggleOff: { backgroundColor: colors.border },
  recentHeader: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    color: 'rgba(241,237,237,0.4)',
    marginTop: 22,
    marginBottom: 8,
  },
  recentItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.bgElevated,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 10,
    marginBottom: 6,
  },
  recentIcon: { marginRight: 8 },
  recentText: { color: colors.tertiary, fontSize: 12, flex: 1 },
  recentEmpty: { color: 'rgba(241,237,237,0.35)', fontSize: 12, fontStyle: 'italic' },
  shareSheetOverlay: {
    flex: 1,
    backgroundColor: 'rgba(11,3,45,0.85)',
    justifyContent: 'center',
    padding: 24,
  },
  shareSheetCard: {
    backgroundColor: colors.bgElevated,
    borderWidth: 1,
    borderColor: colors.secondary,
    borderRadius: 14,
    padding: 20,
  },
  shareSheetTitle: { fontSize: 16, fontWeight: '700', color: colors.tertiary, marginBottom: 8 },
  shareSheetPreview: {
    fontSize: 13,
    color: 'rgba(241,237,237,0.7)',
    backgroundColor: colors.primary,
    borderRadius: 8,
    padding: 10,
    marginBottom: 16,
    maxHeight: 120,
  },
})
